Repository starkyorg/starky, pull requests merged in 2025-03, with the labels that each got.

#145 fix several problems
  pages/examples/index.tsx
  pages/verify/[discordServerId]/[discordMemberId]/[customLink].tsx
  styles/globals.scss
Labels: bug

#148 feat: adding guide to setup db
  README.md
Labels: documentation

#150 fix: discord server relation
  db/entity/DiscordAnalyticsToken.ts
  db/entity/DiscordMember.ts
  db/entity/DiscordServer.ts
  db/entity/DiscordServerConfig.ts
  package.json
Labels: bug

#157 Fix: Replace <img> with <Image /> and install sharp for image optimiz…
  next.config.js
  package-lock.json
  package.json
  pages/verify/[discordServerId]/[discordMemberId]/[customLink].tsx
Labels: Change requested

#163 Fix: Add triangle-prefixed help links to homepage
  pages/index.tsx
  styles/Home.module.scss
Labels: Change requested

#164 Add starky-dashboard command
  db/data-source.ts
  db/entity/DiscordDashboardToken.ts
  db/index.ts
  db/migration/1743266004193-CreateDiscordDashboardTokenTable.ts
  discord/commands/index.ts
  discord/interactions/handleAnalyticsCommand.ts
  discord/interactions/handleDashboardCommand.ts
  utils/database.ts
Labels: Change requested
